services:
  postgres:
    image: postgres:15
    container_name: taskqueue-postgres
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: amardeep
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: taskqueue-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: